ALTER TABLE requests
    ADD CONSTRAINT chk_requests_type
        CHECK (type IN ('VACATION', 'PURCHASE', 'ACCESS', 'INCIDENT', 'OTHER')),
    ADD CONSTRAINT chk_requests_status
        CHECK (status IN ('CREATED', 'IN_REVIEW', 'APPROVED', 'REJECTED', 'CANCELLED')),
    ADD CONSTRAINT chk_requests_title_length
        CHECK (char_length(btrim(title)) BETWEEN 3 AND 120),
    ADD CONSTRAINT chk_requests_description_length
        CHECK (char_length(btrim(description)) BETWEEN 10 AND 2000),
    ADD CONSTRAINT chk_requests_requester_length
        CHECK (char_length(btrim(requester)) BETWEEN 1 AND 120),
    ADD CONSTRAINT chk_requests_justification_length
        CHECK (justification IS NULL OR char_length(justification) <= 1000),
    ADD CONSTRAINT chk_requests_timestamps
        CHECK (updated_at >= created_at);

CREATE INDEX idx_requests_status_created
    ON requests (status, created_at DESC, id ASC);

CREATE INDEX idx_requests_type_status_created
    ON requests (type, status, created_at DESC, id ASC);

CREATE TABLE request_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id BIGINT NOT NULL,
    previous_status VARCHAR(30) NOT NULL,
    new_status VARCHAR(30) NOT NULL,
    changed_by VARCHAR(120) NOT NULL,
    changed_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_request_history_request
        FOREIGN KEY (request_id) REFERENCES requests(id) ON DELETE RESTRICT,
    CONSTRAINT chk_request_history_previous_status
        CHECK (previous_status IN ('CREATED', 'IN_REVIEW', 'APPROVED', 'REJECTED', 'CANCELLED')),
    CONSTRAINT chk_request_history_new_status
        CHECK (new_status IN ('CREATED', 'IN_REVIEW', 'APPROVED', 'REJECTED', 'CANCELLED')),
    CONSTRAINT chk_request_history_changed_by
        CHECK (char_length(btrim(changed_by)) BETWEEN 1 AND 120),
    CONSTRAINT chk_request_history_transition
        CHECK (
            (previous_status = 'CREATED' AND new_status IN ('IN_REVIEW', 'CANCELLED'))
            OR
            (previous_status = 'IN_REVIEW' AND new_status IN ('APPROVED', 'REJECTED', 'CANCELLED'))
        )
);

CREATE INDEX idx_request_history_request_changed
    ON request_history (request_id, changed_at ASC, id ASC);

CREATE TABLE request_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id BIGINT NOT NULL,
    author VARCHAR(120) NOT NULL,
    content VARCHAR(2000) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_request_comments_request
        FOREIGN KEY (request_id) REFERENCES requests(id) ON DELETE CASCADE,
    CONSTRAINT chk_request_comments_author
        CHECK (char_length(btrim(author)) BETWEEN 1 AND 120),
    CONSTRAINT chk_request_comments_content
        CHECK (char_length(btrim(content)) BETWEEN 1 AND 2000)
);

CREATE INDEX idx_request_comments_request_created
    ON request_comments (request_id, created_at ASC, id ASC);

CREATE OR REPLACE FUNCTION prevent_request_history_mutation()
RETURNS TRIGGER AS $$
BEGIN
    RAISE EXCEPTION 'request_history is immutable';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_request_history_immutable
    BEFORE UPDATE OR DELETE ON request_history
    FOR EACH ROW
    EXECUTE FUNCTION prevent_request_history_mutation();
