CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(120) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    display_name VARCHAR(120) NOT NULL,
    role VARCHAR(30) NOT NULL DEFAULT 'USER',
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT chk_users_email_normalized
        CHECK (email = lower(btrim(email)) AND char_length(email) BETWEEN 3 AND 120),
    CONSTRAINT chk_users_password_hash
        CHECK (char_length(password_hash) BETWEEN 60 AND 100),
    CONSTRAINT chk_users_display_name
        CHECK (char_length(btrim(display_name)) BETWEEN 1 AND 120),
    CONSTRAINT chk_users_role
        CHECK (role IN ('USER', 'MANAGER', 'ADMIN')),
    CONSTRAINT chk_users_timestamps
        CHECK (updated_at >= created_at)
);

CREATE INDEX idx_users_role_email
    ON users (role, email ASC);

CREATE INDEX idx_requests_requester_created
    ON requests (lower(requester), created_at DESC, id ASC);
