package com.aprovexa.auth.model;

public enum Permission {
    REQUEST_CREATE,
    REQUEST_READ_OWN,
    REQUEST_READ_ALL,
    REQUEST_UPDATE_OWN,
    REQUEST_DELETE_OWN,
    REQUEST_SUBMIT_OWN,
    REQUEST_CANCEL_OWN,
    REQUEST_REVIEW,
    REQUEST_MANAGE_ALL,
    REQUEST_COMMENT_OWN,
    REQUEST_COMMENT_ALL,
    REQUEST_HISTORY_OWN,
    REQUEST_HISTORY_ALL
}
